import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { realpath } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createInterface } from 'node:readline/promises'
import { OAuth2Scopes, PermissionsBitField } from 'discord.js'

export interface SetupOptions {
  owner?: string
  project?: string
  packageSpec?: string
}

/** Interactive setup: verify Discord, install the dedicated profile, and store the token through DSH. */
export async function setup(options: SetupOptions): Promise<void> {
  assertDsh()
  const io = createInterface({ input: process.stdin, output: process.stdout })
  try {
    const ownerId = options.owner?.trim() || (await io.question('Discord Owner 用户 ID：')).trim()
    if (!/^\d{15,22}$/.test(ownerId)) throw new Error('Discord Owner 必须是数字 snowflake ID。')
    const enteredProject = options.project ?? await io.question(`项目目录（默认 ${process.cwd()}）：`)
    const projectRoot = await realpath(resolve(enteredProject.trim() || process.cwd()))
    io.close()
    const token = process.env.DSH_DISCORD_SETUP_VALUE ?? await readSecret('Discord Bot Token（输入不会回显）：')
    if (token.trim().length === 0) throw new Error('Discord Bot Token 不能为空。')
    process.stdout.write('正在验证 Discord Token…\n')
    const application = await validateDiscordToken(token)
    const packageRoot = fileURLToPath(new URL('../../', import.meta.url))
    const packageSpec = options.packageSpec ?? packageRoot
    runDsh(['plugin', '--profile', 'discord', 'add', packageSpec])
    writeProfilePatch(ownerId, projectRoot)
    runDsh(['--profile', 'discord'], {
      ...process.env,
      DSH_DISCORD_SETUP: '1',
      DSH_DISCORD_SETUP_VALUE: token,
    })
    const permissions = new PermissionsBitField([
      PermissionsBitField.Flags.ViewChannel,
      PermissionsBitField.Flags.SendMessages,
      PermissionsBitField.Flags.ReadMessageHistory,
      PermissionsBitField.Flags.EmbedLinks,
      PermissionsBitField.Flags.AttachFiles,
    ]).bitfield
    const invite = new URL('https://discord.com/oauth2/authorize')
    invite.searchParams.set('client_id', application.id)
    invite.searchParams.set('permissions', String(permissions))
    invite.searchParams.set('scope', `${OAuth2Scopes.Bot} ${OAuth2Scopes.ApplicationsCommands}`)
    process.stdout.write(`\n设置完成。邀请链接：\n${invite.toString()}\n\n启动：dsh-discord start\n`)
  } finally {
    io.close()
  }
}

function assertDsh(): void {
  const result = spawnSync('dsh', ['--help'], { stdio: 'ignore', shell: process.platform === 'win32' })
  if (result.status !== 0) throw new Error('未找到可用的 dsh CLI；请先安装 DeepSeek Harness。')
}

function runDsh(args: string[], env: NodeJS.ProcessEnv = process.env): void {
  const result = spawnSync('dsh', args, { stdio: 'inherit', env, shell: process.platform === 'win32' })
  if (result.status !== 0) throw new Error(`dsh ${args[0] ?? ''} 执行失败。`)
}

function writeProfilePatch(ownerId: string, projectRoot: string): void {
  const home = resolve(process.env.DSH_HOME?.trim() || join(homedir(), '.dsh'))
  const filename = join(home, 'profiles', 'discord', 'cordis.patch.yml')
  if (!existsSync(dirname(filename))) mkdirSync(dirname(filename), { recursive: true })
  const content = [
    '# Generated by dsh-discord setup. Secret values are stored by ctx.credentials, not here.',
    '- id: dsh-discord',
    '  config:',
    '    tokenRef: DSH_DISCORD_BOT_TOKEN',
    `    ownerId: ${JSON.stringify(ownerId)}`,
    `    projectRoot: ${JSON.stringify(projectRoot)}`,
    "    statePath: !!js dshHomePath('dsh-discord', 'state.json')",
    "    setupMode: !!js process.env.DSH_DISCORD_SETUP === '1'",
    "    doctorMode: !!js process.env.DSH_DISCORD_DOCTOR === '1'",
    '    progressIntervalMs: 1500',
    '    interactionTimeoutMs: 600000',
    '',
  ].join('\n')
  writeFileSync(filename, content, { encoding: 'utf8', mode: 0o600 })
}

async function validateDiscordToken(token: string): Promise<{ id: string }> {
  const response = await fetch('https://discord.com/api/v10/oauth2/applications/@me', {
    headers: { authorization: `Bot ${token}` },
  }).catch(() => undefined)
  if (response?.ok !== true) throw new Error('Discord Token 验证失败。')
  const value: unknown = await response.json()
  if (typeof value !== 'object' || value === null || typeof (value as { id?: unknown }).id !== 'string') {
    throw new Error('Discord 应用信息响应无效。')
  }
  return { id: (value as { id: string }).id }
}

async function readSecret(prompt: string): Promise<string> {
  if (!process.stdin.isTTY || !process.stdout.isTTY) {
    const io = createInterface({ input: process.stdin, output: process.stdout })
    try { return await io.question(prompt) } finally { io.close() }
  }
  process.stdout.write(prompt)
  process.stdin.setRawMode(true)
  process.stdin.resume()
  process.stdin.setEncoding('utf8')
  return new Promise<string>((resolveSecret, reject) => {
    let value = ''
    const finish = () => {
      process.stdin.setRawMode(false)
      process.stdin.pause()
      process.stdin.removeListener('data', onData)
      process.stdout.write('\n')
      resolveSecret(value)
    }
    const onData = (chunk: string) => {
      if (chunk === '\r' || chunk === '\n') finish()
      else if (chunk === '\u0003') {
        process.stdin.setRawMode(false)
        process.stdin.removeListener('data', onData)
        reject(new Error('设置已取消。'))
      } else if (chunk === '\u007f' || chunk === '\b') value = value.slice(0, -1)
      else value += chunk
    }
    process.stdin.on('data', onData)
  })
}
